# Generated by Django 5.0.7 on 2025-11-14 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportrun',
            old_name='rows_count',
            new_name='rows',
        ),
        migrations.RemoveField(
            model_name='reportrun',
            name='download_url',
        ),
        migrations.AddField(
            model_name='reportrun',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='sample_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reportrun',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='savedreport',
            name='description',
        ),
        migrations.AddField(
            model_name='savedreport',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='last_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='schedule_cron',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='query_dsl',
            field=models.JSONField(),
        ),
    ]
