# Generated by Django 5.0.0 on 2023-12-01 00:00

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
    ]
