# Generated by Django 5.0.6 on 2024-05-22 BLAH BLAH

from django.db import migrations, models
import pgvector.django
import uuid

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='TextChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(help_text='A descriptive title for the text chunk.', max_length=255)),
                ('body', models.TextField(help_text='The actual text content that is embedded.')),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=1536, help_text='The vector embedding of the text chunk.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata, e.g., source URL, document ID.')),
            ],
            options={
                'verbose_name': 'Text Chunk',
                'verbose_name_plural': 'Text Chunks',
                'indexes': [pgvector.django.HNSWIndex(fields=['embedding'], name='text_chunk_embedding_hnsw_index', opclasses=['vector_l2_ops'])],
            },
        ),
    ]
