# Generated by Django 5.0.6 on 2024-05-22 10:00

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vectorsearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('object_id', models.UUIDField()),
                ('embedding', pgvector.django.VectorField(dimensions=1536)),
                ('source_text', models.TextField(help_text='The text that was embedded')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('content_type', 'object_id')},
                'indexes': [pgvector.django.HNSWIndex(fields=['embedding'], name='embedding_hnsw_index', opclasses=['vector_l2_ops'], m=16, ef_construction=64)],
            },
        ),
    ]
