# Generated by Django 5.0.6 on 2024-05-23 10:00

import django.db.models.deletion
import pgvector.django
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('vectorsearch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('lang', models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], default='fa', max_length=5)),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('page', 'Page'), ('product', 'Product'), ('media', 'Media'), ('other', 'Other')], default='article', max_length=10)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('crawler', 'Crawler'), ('rss', 'RSS Feed'), ('import', 'Import'), ('api', 'API')], default='manual', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpora', to='core.siteprofile')),
            ],
            options={'verbose_name': 'Corpus', 'verbose_name_plural': 'Corpora', 'unique_together': {('site', 'name')}},
        ),
        migrations.CreateModel(
            name='EmbeddingVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('provider', models.CharField(choices=[('mock', 'Mock'), ('openai', 'OpenAI'), ('ollama', 'Ollama'), ('hf', 'HuggingFace')], default='mock', max_length=10)),
                ('model_name', models.CharField(max_length=255)),
                ('dim', models.PositiveIntegerField(help_text='The dimensions of the embedding vector.')),
                ('instruction', models.CharField(blank=True, help_text='Optional instruction prefix for the model.', max_length=512, null=True)),
                ('normalize', models.BooleanField(default=True, help_text='Whether to normalize the embedding vectors.')),
                ('is_active', models.BooleanField(default=False, help_text='Indicates the currently active version for new embeddings.')),
            ],
            options={'verbose_name': 'Embedding Version', 'verbose_name_plural': 'Embedding Versions'},
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('external_id', models.CharField(help_text='The ID of the content in its original source (e.g., Post.id).', max_length=255)),
                ('title', models.CharField(max_length=512)),
                ('raw_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Source-specific metadata like URL, tags, category, etc.')),
                ('hash', models.CharField(help_text='SHA256 hash of the raw_text to detect changes.', max_length=64)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number, incremented on content change.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this document is active for searching.')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vectorsearch.corpus')),
            ],
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents', 'unique_together': {('corpus', 'external_id')}, 'indexes': [models.Index(fields=['corpus', 'external_id'], name='vectorsearc_corpus__e65377_idx')]},
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('ordinal', models.PositiveIntegerField(help_text='The order of the chunk within the document.')),
                ('text', models.TextField()),
                ('tokens', models.PositiveIntegerField(default=0, help_text='Number of tokens in the text.')),
                ('embedding', pgvector.django.VectorField(blank=True, help_text='The vector embedding.', null=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Chunk-specific metadata like headings.')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='vectorsearch.document')),
                ('embedding_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chunks', to='vectorsearch.embeddingversion')),
            ],
            options={'verbose_name': 'Chunk', 'verbose_name_plural': 'Chunks', 'unique_together': {('document', 'ordinal')}, 'indexes': [models.Index(fields=['document', 'ordinal'], name='vectorsearc_documen_12b2d6_idx'), pgvector.django.HNSWIndex(fields=['embedding'], name='chunk_embedding_hnsw_index', opclasses=['vector_l2_ops'])]},
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('query_text', models.TextField()),
                ('mode', models.CharField(choices=[('vector', 'Vector'), ('bm25', 'BM25'), ('hybrid', 'Hybrid'), ('hybrid_rerank', 'Hybrid with Rerank')], max_length=15)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.PositiveIntegerField(help_text='Query execution time in milliseconds.')),
                ('results_count', models.PositiveIntegerField()),
                ('trace_id', models.UUIDField(blank=True, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.siteprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'Query Log', 'verbose_name_plural': 'Query Logs'},
        ),
    ]
