# Generated by Django 5.0.6 on 2024-05-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorsearch', '0003_bm25_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Only active chunks are used in searches.'),
        ),
    ]
