# Generated by Django 5.0.7 on 2025-11-14 06:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('core', '0002_add_org_and_site_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1024, unique=True)),
                ('lang', models.CharField(default='auto', max_length=10)),
                ('purpose', models.CharField(choices=[('monitor', 'Monitor'), ('ingest', 'Ingest'), ('both', 'Both')], default='monitor', max_length=10)),
                ('check_interval_minutes', models.PositiveIntegerField(default=60)),
                ('max_backfill', models.PositiveIntegerField(default=50)),
                ('parser_profile', models.CharField(default='auto', max_length=50)),
                ('content_policy', models.CharField(default='notify', max_length=20)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_sources', to='core.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedRunLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('fetched', models.PositiveIntegerField(default=0)),
                ('new', models.PositiveIntegerField(default=0)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='rss.feedsource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid_hash', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('url', models.URLField(max_length=2048)),
                ('published_at', models.DateTimeField()),
                ('author', models.CharField(blank=True, max_length=255)),
                ('summary_raw', models.TextField(blank=True)),
                ('content_raw', models.TextField(blank=True)),
                ('content_clean', models.TextField(blank=True)),
                ('media', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('processed', 'Processed'), ('skipped', 'Skipped'), ('error', 'Error')], db_index=True, default='new', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.post')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rss.feedsource')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
