# Generated by Django 5.0.6 on 2024-05-24 14:00

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='content.category')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.siteprofile')),
            ],
            options={'verbose_name_plural': 'Categories', 'unique_together': {('site', 'slug')}},
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.CharField(choices=[('ARTICLE', 'Article'), ('PRODUCT', 'Product'), ('PAGE', 'Page')], default='ARTICLE', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=10)),
                ('title', models.CharField(max_length=512)),
                ('title_en', models.CharField(blank=True, help_text='English title, used for generating a clean slug.', max_length=512)),
                ('slug', models.SlugField(allow_unicode=True, max_length=512)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True, help_text='Normalized plain text version of the body for analysis.')),
                ('summary', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('main_keyword', models.CharField(blank=True, max_length=100)),
                ('secondary_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None)),
                ('lsi_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Latent Semantic Indexing keywords.', null=True, size=None)),
                ('entities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Named entities found in the text.', null=True, size=None)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('weight', models.IntegerField(default=0, help_text='A weight for ordering, e.g., for featured posts.')),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('robots_mode', models.CharField(choices=[('INDEX_FOLLOW', 'Index, Follow'), ('NOINDEX_FOLLOW', 'No Index, Follow'), ('INDEX_NOFOLLOW', 'Index, No Follow'), ('NOINDEX_NOFOLLOW', 'No Index, No Follow')], default='INDEX_FOLLOW', max_length=20)),
                ('read_time_min', models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes.')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='content.category')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.siteprofile')),
            ],
            options={'unique_together': {('site', 'slug')}},
        ),
        migrations.CreateModel(
            name='CompetitorURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('url', models.URLField(max_length=2048)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('headings_json', models.JSONField(default=dict, help_text='Extracted H1-H6 headings.')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_fetch_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='content.post')),
            ],
            options={'ordering': ['-created_at'], 'abstract': False},
        ),
        migrations.CreateModel(
            name='FaqBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('order', models.PositiveIntegerField()),
                ('question', models.CharField(max_length=512)),
                ('answer_html', models.TextField()),
                ('has_schema', models.BooleanField(default=True, help_text='If true, generate FAQPage schema.org markup.')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_blocks', to='content.post')),
            ],
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('rev_no', models.PositiveIntegerField()),
                ('diff_json', models.JSONField(help_text='A diff between this revision and the previous one.')),
                ('body_html_snapshot', models.TextField()),
                ('meta_snapshot', models.JSONField(help_text='Snapshot of metadata like title, SEO fields, etc.')),
                ('note', models.CharField(blank=True, help_text='A short note describing the changes.', max_length=255)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='content.post')),
            ],
            options={'unique_together': {('post', 'rev_no')}},
        ),
        migrations.CreateModel(
            name='PostSlugHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('old_slug', models.SlugField(allow_unicode=True, max_length=512)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_history', to='content.post')),
            ],
            options={'verbose_name_plural': 'Post Slug History'},
        ),
        migrations.CreateModel(
            name='Redirect301',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('from_path', models.CharField(db_index=True, max_length=2048)),
                ('to_path', models.CharField(max_length=2048)),
                ('reason', models.CharField(choices=[('SLUG_CHANGE', 'Slug Change'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='core.siteprofile')),
            ],
            options={'unique_together': {('site', 'from_path')}},
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={'ordering': ['-created_at'], 'abstract': False},
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='content.tag'),
        ),
    ]
