# Generated by Django 5.0.6 on 2024-05-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='If set, the post will be published at this time.', null=True),
        ),
    ]
