# Generated by Django 5.0.6 on 2024-05-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_trends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranktimeseries',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ranktimeseries',
            name='ctr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ranktimeseries',
            name='impressions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
