# Generated by Django 5.0.7 on 2025-11-14 01:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('core', '0002_add_org_and_site_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('schema_type', models.CharField(help_text='e.g., Article, BreadcrumbList, FAQPage', max_length=100)),
                ('template', models.JSONField(help_text='Jinja2 template for the JSON-LD schema.')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_templates', to='core.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchemaValidationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField()),
                ('errors', models.JSONField(blank=True, null=True)),
                ('rendered_jsonld', models.JSONField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_validation_logs', to='content.post')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_validation_logs', to='core.site')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema_builder.schematemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchemaRenderCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rendered_jsonld', models.JSONField()),
                ('content_version_hash', models.CharField(max_length=64)),
                ('template_version_hash', models.CharField(max_length=64)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema_cache', to='content.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchemaAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('post_type', 'Post Type'), ('category', 'Category'), ('global', 'Global')], max_length=20)),
                ('post_type', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Lower number means higher priority.')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.category')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_assignments', to='core.site')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schema_builder.schematemplate')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
