# Generated by Django 5.0.7 on 2025-11-14 05:28

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('core', '0002_add_org_and_site_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_key', models.CharField(max_length=512)),
                ('secondaries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), default=list, size=None)),
                ('phrases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), default=list, size=None)),
                ('similarity_k', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MFProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('done', 'Done')], default='idle', max_length=10)),
                ('stage', models.CharField(choices=[('seed', 'Seed'), ('combine', 'Combine'), ('expand', 'Expand'), ('serp', 'SERP Collection'), ('cluster', 'Clustering'), ('lsi_entity', 'LSI & Entity Extraction'), ('prompt', 'Prompt Building'), ('text_gen', 'Text Generation'), ('image_gen', 'Image Generation'), ('publish', 'Publishing')], default='seed', max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Project configuration.')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mf_projects', to='core.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MFLSIEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lsi', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('entities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('method', models.CharField(default='tfidf_spacy', max_length=50)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lsi_entities', to='metaphorge.mfcluster')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsi_entities', to='metaphorge.mfproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MFImagePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('placement', models.CharField(max_length=50)),
                ('position', models.CharField(default='after', max_length=20)),
                ('prompt_text', models.TextField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_plans', to='metaphorge.mfcluster')),
                ('generated_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.media')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_plans', to='metaphorge.mfproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MFDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='metaphorge.mfcluster')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mf_drafts', to='content.post')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='metaphorge.mfproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MFCorpusDoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=1024)),
                ('title', models.CharField(max_length=512)),
                ('raw_html', models.TextField()),
                ('cleaned_text', models.TextField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpus_docs', to='metaphorge.mfcluster')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpus_docs', to='metaphorge.mfproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mfcluster',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='metaphorge.mfproject'),
        ),
        migrations.CreateModel(
            name='MFAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metrics', models.JSONField(default=dict)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='metaphorge.mfproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MFPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_ref', models.CharField(max_length=100)),
                ('prompt_text', models.TextField()),
                ('vars', models.JSONField(default=dict)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='metaphorge.mfcluster')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='metaphorge.mfproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MFSeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('lang', models.CharField(default='auto', max_length=10)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeds', to='metaphorge.mfproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MFSerpResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phrase', models.CharField(max_length=512, unique=True)),
                ('top10', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serp_results', to='metaphorge.mfproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MFCombo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='metaphorge.mfproject')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='metaphorge.mfseed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MFKeywordRaw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phrase', models.CharField(max_length=512)),
                ('source', models.CharField(default='suggest', max_length=20)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metaphorge.mfcombo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_keywords', to='metaphorge.mfproject')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metaphorge.mfseed')),
            ],
            options={
                'unique_together': {('project', 'phrase')},
            },
        ),
        migrations.CreateModel(
            name='MFKeywordExpanded',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phrase', models.CharField(max_length=512)),
                ('depth', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expanded_keywords', to='metaphorge.mfproject')),
                ('parent_raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='metaphorge.mfkeywordraw')),
            ],
            options={
                'unique_together': {('project', 'phrase')},
            },
        ),
    ]
