# Generated by Django 5.0.7 on 2025-11-14 01:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('core', '0002_add_org_and_site_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotsRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_agent', models.CharField(default='*', help_text="e.g., '*', 'Googlebot'", max_length=100)),
                ('path_regex', models.CharField(help_text='A regex for the URL path to apply this rule to.', max_length=512)),
                ('is_allowed', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots_rules', to='core.site')),
            ],
            options={
                'verbose_name': 'Robots Path Rule',
                'ordering': ['path_regex'],
            },
        ),
        migrations.CreateModel(
            name='RobotsGlobal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='The full content of the robots.txt file.')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='robots_global', to='core.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaRobotsOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('noindex', models.BooleanField(default=False)),
                ('nofollow', models.BooleanField(default=False)),
                ('noarchive', models.BooleanField(default=False)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_robots_override', to='content.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
