# Generated by Django 5.0.7 on 2025-11-14 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('core', '0002_add_org_and_site_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('headless_push', 'Headless Push'), ('static_export', 'Static Export'), ('local', 'Local')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict, help_text='Type-specific configuration, e.g., endpoint URL, auth headers, target paths.')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_destinations', to='core.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('unpublish', 'Unpublish')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=10)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('response_snapshot', models.JSONField(blank=True, help_text='Snapshot of the response from the destination.', null=True)),
                ('idempotency_key', models.CharField(help_text='Prevents duplicate jobs for the same content version.', max_length=255, unique=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_jobs', to='content.post')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='publishing.publishdestination')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publishing.publishjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaSyncMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_path', models.CharField(max_length=1024)),
                ('remote_url', models.URLField(blank=True, max_length=1024)),
                ('last_sync_at', models.DateTimeField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_sync_maps', to='content.media')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_maps', to='publishing.publishdestination')),
            ],
            options={
                'unique_together': {('media', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='ContentRenderCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rendered_html', models.TextField()),
                ('rendered_meta', models.JSONField()),
                ('rendered_jsonld', models.JSONField()),
                ('content_version_hash', models.CharField(max_length=64)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='render_cache', to='content.post')),
            ],
            options={
                'verbose_name': 'Content Render Cache',
            },
        ),
        migrations.CreateModel(
            name='PublishMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_id_or_path', models.CharField(help_text='ID for headless, file path for static.', max_length=1024)),
                ('remote_url', models.URLField(blank=True, max_length=1024)),
                ('last_sync_at', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_maps', to='content.post')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='publishing.publishdestination')),
            ],
            options={
                'unique_together': {('post', 'destination')},
            },
        ),
    ]
