# Generated by Django 5.0.7 on 2025-11-14 01:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_org_and_site_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_type', models.CharField(help_text="e.g., 'article', 'product'. Use '*' for all.", max_length=50)),
                ('priority', models.FloatField(default=0.5, help_text='Value between 0.0 and 1.0.')),
                ('changefreq', models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='weekly', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitemap_rules', to='core.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SitemapBuildLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=10)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('url_count', models.PositiveIntegerField(default=0)),
                ('errors', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitemap_build_logs', to='core.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndexationState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=1024, unique=True)),
                ('is_indexed', models.BooleanField(default=False)),
                ('last_checked_at', models.DateTimeField()),
                ('gsc_status', models.CharField(blank=True, max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexation_states', to='core.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HreflangMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(max_length=1024, unique=True)),
                ('alternates', models.JSONField(help_text="e.g., [{'lang': 'en', 'href': 'https://...'}, ...]") ),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hreflang_maps', to='core.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
