# Generated by Django 5.0.7 on 2025-11-14 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('core', '0002_add_org_and_site_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(default='global', max_length=50)),
                ('include', models.JSONField(blank=True, default=dict)),
                ('exclude', models.JSONField(blank=True, default=dict)),
                ('max_links_per_post', models.PositiveIntegerField(default=5)),
                ('min_distance_chars', models.PositiveIntegerField(default=300)),
                ('anchor_strategy', models.CharField(default='exact', max_length=50)),
                ('capitalize_sensitivity', models.BooleanField(default=False)),
                ('allow_multiple_to_same_target', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_rules', to='core.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anchor_text', models.CharField(max_length=255)),
                ('start_idx', models.PositiveIntegerField()),
                ('end_idx', models.PositiveIntegerField()),
                ('context_preview', models.TextField()),
                ('score', models.FloatField()),
                ('reason', models.JSONField(default=dict)),
                ('applied_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_candidates', to='core.site')),
                ('source_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_candidates', to='content.post')),
                ('target_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_candidates', to='content.post')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='LinkBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total', models.PositiveIntegerField()),
                ('applied', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('applying', 'Applying'), ('done', 'Done'), ('aborted', 'Aborted')], default='prepared', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_batches', to='core.site')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autolink.linkrule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
