# Generated by Django 5.0.6 on 2024-05-22 12:30

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', 'models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.CharField(choices=[('GSC', 'Google Search Console'), ('GA4', 'Google Analytics 4'), ('PSE', 'Programmable Search Engine'), ('OLLAMA', 'Ollama'), ('SD', 'Stable Diffusion')], help_text='The type of the external service.', max_length=10, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('ERROR', 'Error')], default='DISABLED', help_text='The current status of the connector.', max_length=10)),
                ('credentials_encrypted', models.TextField(blank=True, help_text='Encrypted credentials for the service (e.g., API key, OAuth token).')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful data sync.', null=True)),
                ('last_error_message', models.TextField(blank=True, help_text='Details of the last error encountered.')),
                ('quota_used', models.PositiveIntegerField(default=0)),
                ('quota_total', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
